stages:
  - test
  - build
  - deploy

.go-cache:
  before_script:
    - export GOPATH=/go
    - export GOPRIVATE=*.city-srv.ru
    - export GOPROXY=direct
    - go mod tidy -v

Linters:
  extends: .go-cache
  stage: test
  image: golang:1.14
  script:
    - make lint-install
    - make lint
  tags:
    - docker

Tests:
  extends: .go-cache
  stage: test
  image: golang:1.14
  script:
    - make test
  tags:
    - docker

Coverage:
  extends: .go-cache
  stage: test
  image: golang:1.14
  script:
    - make test-coverage
  tags:
    - docker

build_docker:
  stage: build
  image: docker:18-git
  services:
    - docker:18-dind
  script:
    - docker login $CI_REGISTRY -u gitlab-ci-token -p $CI_JOB_TOKEN
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG -f Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  tags:
    - docker
  only:
    refs:
      - master
      - staging

deploy:
  stage: deploy
  image: vandersex/ssh_client:latest
  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ./deploy/deploy.sh
  dependencies:
    - build_docker
  tags:
    - docker
  only:
    refs:
      - master
      - staging