run:
  go: '1.22'

# https://golangci-lint.run/usage/linters/
linters:
  enable:
    - bodyclose
    - decorder
    - dupl
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - gci
    - goconst
    - gofumpt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - ireturn
    - maintidx
    - makezero
    - nilerr
    - nilnil
    - nlreturn
    - perfsprint
    - prealloc
    - predeclared
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - testifylint
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl

linters-settings:
  gci:
    sections:
      - standard
      - blank
      - default
      - blank
      - prefix(github.com/devbackend/goingot) # Don't forget change this line for your mod name
  nlreturn:
    block-size: 2
  exhaustruct:
    exclude:
      - '.+/pkg/http/sender\.ErrorResponse'